development:
  adapter: postgresql
  encoding: unicode
  database: af_development                
  pool: 5
  username: postgres
  password: root
  host: localhost



production:
  adapter: postgresql
  encoding: unicode
  database: afriends                
  pool: 5
  username: postgres
  password: 12345678
  host: localhost
