application_name: afriends
application_version: 1.0.0



# client.authorization.client_id = '471915587883-nb1k2lrh1oubv53eufiqdudfft2b8f9g.apps.googleusercontent.com'
# client.authorization.client_secret = 'k1RHjHROMZOOs0MHxUWLwb3c'
# client.authorization.access_token = 'ya29.pAKz3RyUleC787MXy7PQ0UBMQ6TwgSLgQ5NZRXey0SQzPw_VP4kNqvT3JvhPJAGYJA'
# client.authorization.refresh_token = '1/6etdCEeswirUhBu-6ruOeQvnKnIURFdq6TtsSdBcTuM'


# client_id: <%= ENV["GOOGLE_DRIVE_CLIENT_ID"] %>
# client_secret: <%= ENV["GOOGLE_DRIVE_CLIENT_SECRET"] %>
# access_token: <%= ENV["GOOGLE_DRIVE_ACCESS_TOKEN"] %>
# refresh_token: <%= ENV["GOOGLE_DRIVE_REFRESH_TOKEN"] %>


client_id: "471915587883-7v1b155ungee9vpg945b7vn62rssk46i.apps.googleusercontent.com"
client_secret: "nRPMfcu4sdodAqz1w02tJX-Y"
access_token: "ya29.pALA-ky85UEmvoAPoyns6zFWFF_OQcFt5n2duG52j87uF45K3ZhmxH37dfwTZys92g"
refresh_token: "1/CiY2zP0QJBuXmrNdGDw-pUzq49gCOwKYqHU9-dlMEr8"
pulic_folder: "0B4d-BosofnhbZncyNG1kbUM3bFE"
