application_name: afriends
application_version: 1.0.0



# client.authorization.client_id = '471915587883-nb1k2lrh1oubv53eufiqdudfft2b8f9g.apps.googleusercontent.com'
# client.authorization.client_secret = 'k1RHjHROMZOOs0MHxUWLwb3c'
# client.authorization.access_token = 'ya29.pAKz3RyUleC787MXy7PQ0UBMQ6TwgSLgQ5NZRXey0SQzPw_VP4kNqvT3JvhPJAGYJA'
# client.authorization.refresh_token = '1/6etdCEeswirUhBu-6ruOeQvnKnIURFdq6TtsSdBcTuM'


# client_id: <%= ENV["GOOGLE_DRIVE_CLIENT_ID"] %>
# client_secret: <%= ENV["GOOGLE_DRIVE_CLIENT_SECRET"] %>
# access_token: <%= ENV["GOOGLE_DRIVE_ACCESS_TOKEN"] %>
# refresh_token: <%= ENV["GOOGLE_DRIVE_REFRESH_TOKEN"] %>

client_id: "742084394503-iau3jl2r55c5d4889f8dmoc49tk5amag.apps.googleusercontent.com"
client_secret: "TQxGjjAVHX1feC-QC8xcWzTm"
access_token: "ya29.CjHhAgO18y-d65jYMC6WXmCesVDphAo4n_DJBpHCBn0kGQAMdvEgHCYiMp3zlJVPhhl5"
refresh_token: "1/YgJkuCNnqsK3fiepDzIW4zIbcdJoaxGdjmu1C86FUhUMEudVrK5jSpoR30zcRFq6"
pulic_folder: "0B3-wKP83_thWanZaVlJSUGxYLW8"
