# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.




development:
  secret_key_base: 9a8d8a5452dd364b0e4d6c301a589bcab1d801119d3c315c2d3f954e5d4a76a36ad2aec5431b02d2d4a5bcb43ba41d67ddb309e8079b593d3a57e2791ee0ec53

test:
  secret_key_base: ef002d740d495883790b4a8e5cfa100f2b53420cfb0aba94cc48841a9835743989ceeabe95e0f9f1d1fd4caae6678d5108c3ecf8cd661d28b4e539e4c787daf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>



